#!/usr/bin/env python3
"""
gen_obf.py — Compile-time string obfuscation preprocessor.

Usage: python3 gen_obf.py <build_src_dir> <hex_key>
  <build_src_dir>  path to the source tree copy (e.g. /tmp/taburtuai-c-xxx)
  <hex_key>        1-byte XOR key as hex string, e.g. "a7"

Actions:
  1. Scan all .c files under <build_src_dir>/src for OBFSTR("...") and
     WOBFSTR("...", buf, cap) patterns.
  2. Replace OBFSTR("x")         -> _obf_get(N)
     Replace WOBFSTR("x", b, c)  -> _obf_fill_w(N, b, c)
     where N is the stable index into the shared encoded string table.
  3. Write <build_src_dir>/src/obf_table.c with XOR-encoded string table
     plus ObfInit(), _obf_get(), and _obf_fill_w() implementations.
  4. Print "[obf] N strings encoded with key 0xKK" on success.
"""

import sys
import os
import re
import codecs

def main():
    if len(sys.argv) < 3:
        print("usage: gen_obf.py <build_src_dir> <hex_key>", file=sys.stderr)
        sys.exit(1)

    src_dir = sys.argv[1]
    hex_arg = sys.argv[2].strip()
    if len(hex_arg) != 32:
        print(f"error: hex_key must be 32 hex chars (16 bytes), got {len(hex_arg)}", file=sys.stderr)
        sys.exit(1)
    key = bytes.fromhex(hex_arg)

    # Patterns
    # OBFSTR("literal")
    pat_obf = re.compile(r'OBFSTR\("((?:[^"\\]|\\.)*)"\)')
    # WOBFSTR("literal", buf_expr, cap_expr)
    # arg2 and arg3 are simple expressions (no nested parens in practice)
    pat_wobf = re.compile(r'WOBFSTR\("((?:[^"\\]|\\.)*)",\s*([^,]+?)\s*,\s*([^)]+?)\s*\)')

    # ── First pass: collect all unique strings (preserving first-seen order) ──
    strings_ordered = []
    strings_index   = {}

    c_files = []
    for root, dirs, files in os.walk(os.path.join(src_dir, 'src')):
        for f in files:
            if f.endswith('.c'):
                c_files.append(os.path.join(root, f))

    def decode_raw(raw):
        try:
            return codecs.decode(raw.replace("\\'", "'"), 'unicode_escape')
        except Exception:
            return raw

    def intern_string(s):
        if s not in strings_index:
            strings_index[s] = len(strings_ordered)
            strings_ordered.append(s)
        return strings_index[s]

    for fpath in sorted(c_files):
        with open(fpath, 'r', encoding='utf-8', errors='replace') as fh:
            content = fh.read()
        for m in pat_obf.finditer(content):
            intern_string(decode_raw(m.group(1)))
        for m in pat_wobf.finditer(content):
            intern_string(decode_raw(m.group(1)))

    # ── Second pass: replace patterns in each file ───────────────────────────
    for fpath in sorted(c_files):
        with open(fpath, 'r', encoding='utf-8', errors='replace') as fh:
            content = fh.read()

        def replace_obf(m):
            return f'_obf_get({intern_string(decode_raw(m.group(1)))})'

        def replace_wobf(m):
            idx  = intern_string(decode_raw(m.group(1)))
            buf  = m.group(2).strip()
            cap  = m.group(3).strip()
            return f'_obf_fill_w({idx}, {buf}, {cap})'

        new_content = pat_obf.sub(replace_obf, content)
        new_content = pat_wobf.sub(replace_wobf, new_content)

        if new_content != content:
            with open(fpath, 'w', encoding='utf-8') as fh:
                fh.write(new_content)

    # ── Generate obf_table.c ─────────────────────────────────────────────────
    n = len(strings_ordered)
    key_arr = ', '.join(f'0x{b:02X}' for b in key)
    lines = [
        '/* obf_table.c — AUTO-GENERATED by tools/gen_obf.py. DO NOT EDIT. */',
        '#include "../include/obfstr.h"',
        '#include <string.h>',
        '',
        f'static const unsigned char _obf_key[16] = {{{key_arr}}};',
        f'#define _OBF_COUNT {n}',
        '',
    ]

    # Emit encoded byte arrays (rolling 16-byte XOR)
    for idx, s in enumerate(strings_ordered):
        encoded = [(ord(c) ^ key[i % 16]) & 0xFF for i, c in enumerate(s)]
        encoded += [key[len(s) % 16] ^ 0]   # XOR null terminator
        arr = ', '.join(f'0x{b:02X}' for b in encoded)
        preview = s[:50].replace('\n', '\\n').replace('\r', '\\r')
        lines.append(f'/* [{idx}] "{preview}{"..." if len(s) > 50 else ""}" */')
        lines.append(f'static const unsigned char _e{idx}[] = {{{arr}}};')

    lines += [
        '',
        'static const ObfEntry s_tbl[] = {',
    ]
    for idx, s in enumerate(strings_ordered):
        lines.append(f'    {{ _e{idx}, {len(s)+1} }},')
    lines += [
        '};',
        '',
        '/* Decoded cache — written once by ObfInit(), then effectively read-only */',
        f'static char          s_dec[_OBF_COUNT][256];',
        f'static unsigned char s_ready[_OBF_COUNT];',
        '',
        'static void _decode_entry(int i) {',
        '    const ObfEntry *e = &s_tbl[i];',
        '    int lim = e->len < 255 ? e->len : 255;',
        '    for (int j = 0; j < lim; j++)',
        '        s_dec[i][j] = (char)(e->data[j] ^ _obf_key[j % 16]);',
        '    s_dec[i][lim] = \'\\0\';',
        '    s_ready[i] = 1;',
        '}',
        '',
        'void ObfInit(void) {',
        '    for (int i = 0; i < _OBF_COUNT; i++)',
        '        _decode_entry(i);',
        '}',
        '',
        'const char *_obf_get(int idx) {',
        '    if (idx < 0 || idx >= _OBF_COUNT) return "";',
        '    if (!s_ready[idx]) _decode_entry(idx);',
        '    return s_dec[idx];',
        '}',
        '',
        'void _obf_fill_w(int idx, WCHAR *out, int cap) {',
        '    const char *s = _obf_get(idx);',
        '    int i = 0;',
        '    while (s[i] && i < cap - 1) { out[i] = (WCHAR)(unsigned char)s[i]; i++; }',
        '    out[i] = 0;',
        '}',
    ]

    out_path = os.path.join(src_dir, 'src', 'obf_table.c')
    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')

    print(f'[obf] {n} strings encoded with key {sys.argv[2]}')

if __name__ == '__main__':
    main()
