#!/usr/bin/env python3
"""
gen_obf.py — Compile-time string obfuscation preprocessor.

Usage: python3 gen_obf.py <build_src_dir> <hex_key>
  <build_src_dir>  path to the source tree copy (e.g. /tmp/taburtuai-c-xxx)
  <hex_key>        1-byte XOR key as hex string, e.g. "a7"

Actions:
  1. Scan all .c files under <build_src_dir>/src for OBFSTR("...") patterns.
  2. Replace each occurrence with _obf_get(N) where N is a stable index.
  3. Write <build_src_dir>/src/obf_table.c with XOR-encoded string table.
  4. Print "[obf] N strings encoded with key 0xKK" on success.
"""

import sys
import os
import re
import codecs

def main():
    if len(sys.argv) < 3:
        print("usage: gen_obf.py <build_src_dir> <hex_key>", file=sys.stderr)
        sys.exit(1)

    src_dir = sys.argv[1]
    key = int(sys.argv[2], 16) & 0xFF

    # Pattern matches OBFSTR("...") including escaped chars inside the string
    pattern = re.compile(r'OBFSTR\("((?:[^"\\]|\\.)*)"\)')

    # First pass: collect all unique strings (preserving first-seen order)
    strings_ordered = []
    strings_index   = {}

    c_files = []
    for root, dirs, files in os.walk(os.path.join(src_dir, 'src')):
        for f in files:
            if f.endswith('.c'):
                c_files.append(os.path.join(root, f))

    for fpath in sorted(c_files):
        with open(fpath, 'r', encoding='utf-8', errors='replace') as fh:
            content = fh.read()
        for m in pattern.finditer(content):
            raw = m.group(1)
            # Decode simple C escape sequences
            try:
                s = codecs.decode(raw.replace("\\'", "'"), 'unicode_escape')
            except Exception:
                s = raw
            if s not in strings_index:
                strings_index[s] = len(strings_ordered)
                strings_ordered.append(s)

    # Second pass: replace OBFSTR("...") in each file
    for fpath in sorted(c_files):
        with open(fpath, 'r', encoding='utf-8', errors='replace') as fh:
            content = fh.read()

        def replace_match(m):
            raw = m.group(1)
            try:
                s = codecs.decode(raw.replace("\\'", "'"), 'unicode_escape')
            except Exception:
                s = raw
            return f'_obf_get({strings_index[s]})'

        new_content = pattern.sub(replace_match, content)
        if new_content != content:
            with open(fpath, 'w', encoding='utf-8') as fh:
                fh.write(new_content)

    # Generate obf_table.c
    n = len(strings_ordered)
    lines = [
        '/* obf_table.c — AUTO-GENERATED by tools/gen_obf.py. DO NOT EDIT. */',
        '#include "../include/obfstr.h"',
        '#include <string.h>',
        '',
        f'#define _OBF_KEY 0x{key:02X}u',
        f'#define _OBF_COUNT {n}',
        '',
    ]

    # Emit encoded byte arrays
    for idx, s in enumerate(strings_ordered):
        encoded = [(ord(c) ^ key) & 0xFF for c in s] + [key ^ 0]  # XOR null terminator
        arr = ', '.join(f'0x{b:02X}' for b in encoded)
        preview = s[:50].replace('\n','\\n').replace('\r','\\r')
        lines.append(f'/* [{idx}] "{preview}{"..." if len(s)>50 else ""}" */')
        lines.append(f'static const unsigned char _e{idx}[] = {{{arr}}};')

    lines += [
        '',
        'static const ObfEntry s_tbl[] = {',
    ]
    for idx, s in enumerate(strings_ordered):
        lines.append(f'    {{ _e{idx}, {len(s)+1} }},')
    lines += [
        '};',
        '',
        '/* Decoded cache — written once by ObfInit(), then read-only */',
        f'static char s_dec[_OBF_COUNT][256];',
        f'static unsigned char s_ready[_OBF_COUNT];',
        '',
        'void ObfInit(void) {',
        '    for (int i = 0; i < _OBF_COUNT; i++) {',
        '        const ObfEntry *e = &s_tbl[i];',
        '        int lim = e->len < 255 ? e->len : 255;',
        '        for (int j = 0; j < lim; j++)',
        '            s_dec[i][j] = (char)(e->data[j] ^ _OBF_KEY);',
        '        s_dec[i][lim] = \'\\0\';',
        '        s_ready[i] = 1;',
        '    }',
        '}',
        '',
        'const char *_obf_get(int idx) {',
        '    if (idx < 0 || idx >= _OBF_COUNT) return "";',
        '    if (!s_ready[idx]) {',
        '        /* lazy decode if ObfInit() missed this entry */',
        '        const ObfEntry *e = &s_tbl[idx];',
        '        int lim = e->len < 255 ? e->len : 255;',
        '        for (int j = 0; j < lim; j++)',
        '            s_dec[idx][j] = (char)(e->data[j] ^ _OBF_KEY);',
        '        s_dec[idx][lim] = \'\\0\';',
        '        s_ready[idx] = 1;',
        '    }',
        '    return s_dec[idx];',
        '}',
    ]

    out_path = os.path.join(src_dir, 'src', 'obf_table.c')
    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')

    print(f'[obf] {n} strings encoded with key 0x{key:02X}')

if __name__ == '__main__':
    main()
